Repository Hack-Your-Learning/hackyourlearning-site, pull requests merged in 2021-01, with the labels that each got.

#3 [HW-5] [Other] Navbar & Other Events Page
  .env
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/assets/Light_Logo.png
  src/assets/Light_Logo_Text.png
  src/assets/sessions/github.png
  src/assets/sessions/sec.png
  src/components/HYLButton.jsx
  src/components/LandingBanner.jsx
  src/components/Navbar.jsx
  src/components/Routes.jsx
  src/components/SessionCard.jsx
  src/components/SessionModal.jsx
  src/index.scss
  src/pages/LandingPage.jsx
  src/pages/OtherEventsPage.jsx
  src/stylesheets/HYLButton.scss
  src/stylesheets/LandingPage.scss
  src/stylesheets/OtherEventsPage.scss
  src/stylesheets/SessionCard.scss
  src/stylesheets/SessionModal.scss
  src/stylesheets/navbar/Navbar.scss
  src/stylesheets/navbar/NavbarMobile.scss
Labels: Status: Completed, Type: Enhancement

#7 [HW-10] [Updated] Implementation of Landing Page Banner
  .github/workflows/firebase-hosting-merge.yml
  src/components/LandingBanner.jsx
  src/components/LandingCountdown.jsx
  src/components/SessionModal.jsx
  src/pages/LandingPage.jsx
  src/stylesheets/LandingBanner.scss
Labels: Status: Review Needed, Type: Enhancement

#19 Completed the write-ups for Other Events page
  src/pages/OtherEventsPage.jsx
  src/stylesheets/SessionModal.scss
Labels: Status: Review Needed, Type: Maintenance

#20 Added Sign Up Links
  src/components/LandingBanner.jsx
Labels: Status: Completed, Type: Maintenance

#21 Added about and schedule section
  src/assets/about-img.png
  src/assets/schulich.png
  src/components/About.jsx
  src/pages/LandingPage.jsx
  src/stylesheets/About.scss
  src/stylesheets/LandingBanner.scss
  src/stylesheets/LandingPage.scss
Labels: Status: In Progress, Status: Review Needed, Type: Enhancement

#24 [HW-11][HW-13] About and Schedule Section
  src/assets/about-img.png
  src/assets/schulich.png
  src/components/About.jsx
  src/pages/LandingPage.jsx
  src/stylesheets/About.scss
  src/stylesheets/LandingBanner.scss
  src/stylesheets/LandingPage.scss
Labels: Type: Enhancement

#27 [HW-6] Add footer to landing page
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/HYL_code_of_conduct.pdf
  src/components/Footer.jsx
  src/index.scss
  src/pages/LandingPage.jsx
  src/pages/OtherEventsPage.jsx
  src/stylesheets/Footer.scss
Labels: Status: Review Needed, Type: Enhancement
